# Generated by Django 4.1.2 on 2022-10-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(default='placeholder.jpg', max_length=300),
        ),
    ]
