# Generated by Django 4.1.3 on 2022-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='writter',
            field=models.BooleanField(default=0),
        ),
    ]
