# Generated by Django 4.1.2 on 2022-10-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0004_alter_post_writter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
