# Generated by Django 4.1.2 on 2022-10-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0005_rename_groups_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
