# Generated by Django 4.1.3 on 2022-11-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0005_remove_user_icon_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
