# Generated by Django 4.1.2 on 2022-10-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0007_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
