# Generated by Django 4.1.3 on 2022-11-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinalProject', '0010_alter_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='placeholder.jpg', upload_to='usersicons'),
        ),
    ]
